# Generated by Django 5.0.4 on 2024-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentications', '0008_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('startup', 'Startup'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
